// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function either_of_option(failure, opt) {
  if (opt !== undefined) {
    return /* Result */Block.__(1, [Caml_option.valFromOption(opt)]);
  } else {
    return /* Failure */Block.__(0, [failure]);
  }
}

function lookup(key, _assoc) {
  while(true) {
    var assoc = _assoc;
    if (assoc) {
      var match = assoc[0];
      if (Caml_obj.caml_equal(match[0], key)) {
        return Caml_option.some(match[1]);
      } else {
        _assoc = assoc[1];
        continue ;
      }
    } else {
      return ;
    }
  };
}

exports.either_of_option = either_of_option;
exports.lookup = lookup;
/* No side effect */
